### ISSUE TITLE
Varnish Service 

### ISSUE THREAD

**Issue by arun81** [duy13/VDVARNISH#1]
Hi Team 

Thanks for Varnish Project .

Installed Varnish in Centos .

But when we are enabling the service getting the following error message . Varnish Version selected is 6 at the time of Installation .

[root@localhost ~]# systemctl status varnish.service
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/usr/lib/systemd/system/varnish.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2018-07-01 17:44:04 EDT; 40s ago
  Process: 24830 ExecStart=/usr/sbin/varnishd -P /var/run/varnish.pid -f $VARNISH_VCL_CONF -a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} -S $VARNISH_SECRET_FILE -s $VARNISH_STORAGE $DAEMON_OPTS (code=exited, status=255)

Jul 01 17:44:04 localhost.localdomain systemd[1]: Starting Varnish Cache, a high-performance HTTP accelerator...
Jul 01 17:44:04 localhost.localdomain varnishd[24830]: Error: Could not get socket :80: Address already in use
Jul 01 17:44:04 localhost.localdomain varnishd[24830]: (-? gives usage)
Jul 01 17:44:04 localhost.localdomain systemd[1]: varnish.service: control process exited, code=exited status=255
Jul 01 17:44:04 localhost.localdomain systemd[1]: Failed to start Varnish Cache, a high-performance HTTP accelerator.
Jul 01 17:44:04 localhost.localdomain systemd[1]: Unit varnish.service entered failed state.
Jul 01 17:44:04 localhost.localdomain systemd[1]: varnish.service failed.

**Comment by arun81** [comment]
Output from Varnish Server 

[root@localhost system]# varnishd -V
varnishd (varnish-6.0.0 revision a068361dff0d25a0d85cf82a6e5fdaf315e06a7d)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS

**Comment by duy13** [comment]
`Error: Could not get socket :80: Address already in use`

==> Check which ports are available to listen on the server:

`netstat -lntup|grep 80; netstat -lntup|grep 443`
`netstat -lntup|grep httpd; netstat -lntup|grep nginx`

**Comment by duy13** [comment]
```
cat /etc/varnish/varnish.params|grep VARNISH_LISTEN_PORT
cat /etc/varnish/default.vcl| grep XXXX
```

**Comment by arun81** [comment]
[root@localhost system]# netstat -lntup|grep 80
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1380/master
tcp6       0      0 ::1:25                  :::*                    LISTEN      1380/master
[root@localhost system]# netstat -lntup|grep 443
[root@localhost system]# netstat -lntup|grep httpd
[root@localhost system]# netstat -lntup|grep nginx
[root@localhost system]#

**Comment by arun81** [comment]
[root@localhost /]# cat etc/varnish/varnish.params|grep VARNISH_LISTEN_PORT
VARNISH_LISTEN_PORT=80

**Comment by duy13** [comment]
Please PM support my **skype voduy13**

**Comment by duy13** [comment]
just disable SELINUX

**Comment by duy13** [comment]
Solved!

**Comment by arun81** [comment]
Thanks for Support...
